In [1]:
import numpy as np

In [5]:
lst = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
#Python list to Numpy array
arr = np.array(lst)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#create numpy array from range
np.arange(0,10) #arange(start, end)
np.arange(0,10,2) #arange(start, end, steps)

array([0, 2, 4, 6, 8])

In [14]:
#create array with n elements that have equal spacing between
np.linspace(0,10,111) #linspace(start,stop,n)

array([ 0.        ,  0.09090909,  0.18181818,  0.27272727,  0.36363636,
        0.45454545,  0.54545455,  0.63636364,  0.72727273,  0.81818182,
        0.90909091,  1.        ,  1.09090909,  1.18181818,  1.27272727,
        1.36363636,  1.45454545,  1.54545455,  1.63636364,  1.72727273,
        1.81818182,  1.90909091,  2.        ,  2.09090909,  2.18181818,
        2.27272727,  2.36363636,  2.45454545,  2.54545455,  2.63636364,
        2.72727273,  2.81818182,  2.90909091,  3.        ,  3.09090909,
        3.18181818,  3.27272727,  3.36363636,  3.45454545,  3.54545455,
        3.63636364,  3.72727273,  3.81818182,  3.90909091,  4.        ,
        4.09090909,  4.18181818,  4.27272727,  4.36363636,  4.45454545,
        4.54545455,  4.63636364,  4.72727273,  4.81818182,  4.90909091,
        5.        ,  5.09090909,  5.18181818,  5.27272727,  5.36363636,
        5.45454545,  5.54545455,  5.63636364,  5.72727273,  5.81818182,
        5.90909091,  6.        ,  6.09090909,  6.18181818,  6.27

In [15]:
#numpy identity metrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#numpy ransom array
np.random.rand(2,2,2) #u can make any dimentions

array([[[0.85994244, 0.81069829],
        [0.07096082, 0.39547221]],

       [[0.99890938, 0.35784929],
        [0.06743457, 0.60609141]]])

In [21]:
#numpy random number
np.random.randint(1,10) #singe value 
np.random.randint(1,10,2) #randint(start,end, number of values) 

array([5, 9])

In [23]:
arr = np.random.randint(0,50,15)

In [27]:
#reshape 1 d array to (m,n) d
arr = arr.reshape(5,3)

In [28]:
#get max value from arrary
arr.max()
#get min value from array
arr.min()

0

In [29]:
arr

array([[ 7, 43,  0],
       [27, 32, 19],
       [24,  3,  3],
       [20, 18, 43],
       [45, 19, 38]])

In [36]:
arr = arr.reshape(1,15)

In [38]:
arr = arr[0]

In [39]:
arr

array([ 7, 43,  0, 27, 32, 19, 24,  3,  3, 20, 18, 43, 45, 19, 38])